### ISSUE TITLE
chart.js hover information shows variable name

### ISSUE THREAD

**Issue by leo-hsk** [antonroesler/application-landscape-visualizer#107]
![image](https://user-images.githubusercontent.com/52975667/122022469-e7bbdf00-cdc6-11eb-8ec2-1b59b95ff64c.png)
Should show the ui name

**Comment by leo-hsk** [comment]
@antonroesler we need to talk about this, because it also interferes with filtering from histogram

**Comment by antonroesler** [comment]
Are you still working on this? I have a solution that is working. If you're not working on this i could push it.

**Comment by antonroesler** [comment]
We can either do this:
![Bildschirmfoto 2021-07-07 um 20 18 59](https://user-images.githubusercontent.com/45258920/124809592-91beff00-df60-11eb-9c05-8b118d6ecb45.png)
Or that:
![Bildschirmfoto 2021-07-07 um 20 19 49](https://user-images.githubusercontent.com/45258920/124809692-b024fa80-df60-11eb-9ef9-50880a5d9046.png)

What do you think? Im not sure if its necessary or even good to have the name of the Attribute in the tooltip since it is in the title.

**Comment by leo-hsk** [comment]
Looks good. It is fine to have just the number in the tooltip.
