### ISSUE TITLE
Color-dot in legend is not a circle 

### ISSUE THREAD

**Issue by antonroesler** [antonroesler/application-landscape-visualizer#150]
<img width="172" alt="Bildschirmfoto 2021-06-25 um 20 01 03" src="https://user-images.githubusercontent.com/45258920/123466816-13716d00-d5f0-11eb-969b-2e1b0990f035.png">
In some cases the color dot is not a circle.

**Comment by antonroesler** [comment]
For some stupid reason it gets stretched.

**Comment by leo-hsk** [comment]
Fixed in next pull request

**Comment by leo-hsk** [comment]
Design decision: 
Maybe we can use squares because most parts of the sidebar have also edges.
![image](https://user-images.githubusercontent.com/52975667/124964199-03f71880-e021-11eb-9125-4e35a33fd791.png)
And is there a way to center the whole legend? There is less space on the left side then on the right. Would be nice if it was equal. What do you think @antonroesler

**Comment by antonroesler** [comment]
I think squares do not fit our overall style

**Comment by antonroesler** [comment]
And basically this is centered. But i can try something else.
